import { Check, ExternalLink, Phone, RefreshCw } from "lucide-react";
interface Props { phone:string; captcha:string; captchaCode:string; policyViewed:boolean; consent:boolean; loading:boolean; error:string; onPhoneChange:(v:string)=>void; onCaptchaChange:(v:string)=>void; onRefreshCaptcha:()=>void; onOpenPolicy:()=>void; onConsentChange:(v:boolean)=>void; onSubmit:()=>void; }
export function PhoneLoginForm(p:Props) {
  const ready=/^0[689]\d{8}$/.test(p.phone)&&p.captcha.toUpperCase()===p.captchaCode&&p.consent;
  return <form className="px-4" onSubmit={(e)=>{e.preventDefault();p.onSubmit();}} noValidate>
    <h1 className="text-xl font-bold leading-6">เข้าสู่ระบบ / ลงทะเบียน</h1><p className="mt-2 text-sm text-muted">กรุณากรอกเบอร์มือถือ</p>
    <div className="mt-[11px] flex h-[52px] items-center rounded-[10px] border border-border bg-white"><span className="px-[17px] text-base font-semibold">+66</span><span className="h-8 w-px bg-border" /><label htmlFor="phone" className="sr-only">เบอร์มือถือ</label><input id="phone" type="tel" inputMode="numeric" autoComplete="tel-national" value={p.phone} onChange={(e)=>p.onPhoneChange(e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="08x-xxx-xxx" className="min-w-0 flex-1 bg-transparent px-4 text-base outline-none placeholder:text-[#A1ABBA]" /><Phone aria-hidden className="mr-[14px] h-[18px] w-[18px] text-[#DC2626]" fill="currentColor" /></div>
    <div className="mt-3 flex h-12 overflow-hidden rounded-lg border border-border bg-white"><label htmlFor="captcha" className="sr-only">รหัสยืนยันรูปภาพ</label><input id="captcha" value={p.captcha} onChange={(e)=>p.onCaptchaChange(e.target.value.slice(0,5))} placeholder="กรุณาใส่รหัสยืนยันรูปภาพ" autoComplete="off" className="min-w-0 flex-1 px-3 text-[13px] outline-none placeholder:text-[#A1ABBA]" /><div className="flex w-[139px] items-center bg-[#F2F5FA] pl-[25px]"><strong className="text-base tracking-wide">{p.captchaCode}</strong><button type="button" onClick={p.onRefreshCaptcha} aria-label="เปลี่ยนรหัสยืนยัน" className="ml-auto mr-3 text-action"><RefreshCw className="h-5 w-5" /></button></div></div>
    <p className="mt-1 text-xs text-muted">กรุณาใส่รหัสยืนยันรูปภาพ</p>
    <div className="mt-[14px] grid grid-cols-[20px_1fr] gap-x-[10px]"><button type="button" disabled={!p.policyViewed} onClick={()=>p.onConsentChange(!p.consent)} role="checkbox" aria-checked={p.consent} aria-label="ยอมรับนโยบายการคุ้มครองข้อมูลส่วนบุคคล" className={`mt-px flex h-5 w-5 items-center justify-center rounded border-[1.5px] ${p.consent?"border-action bg-action text-white":p.policyViewed?"border-action bg-white":"cursor-not-allowed border-[#BDC7D6] bg-white"}`}>{p.consent?<Check className="h-4 w-4" strokeWidth={3}/>:null}</button><p className={`text-[11px] leading-[14px] ${p.policyViewed?"text-ink":"text-[#BDC7D6]"}`}>ฉันได้อ่านและเข้าใจนโยบายการคุ้มครองข้อมูลส่วนบุคคลแล้ว</p><button type="button" onClick={p.onOpenPolicy} className="col-start-2 mt-2 flex w-fit items-center gap-1 text-left text-xs font-semibold text-action">ดูนโยบายการคุ้มครองข้อมูลส่วนบุคคล <ExternalLink className="h-[15px] w-[15px]"/></button><p className={`col-start-2 mt-2 text-[10px] ${p.policyViewed?"font-medium text-action":"text-muted"}`}>{p.policyViewed?"อ่านนโยบายแล้ว — สามารถเลือกช่องยอมรับได้":"กรุณาเปิดอ่านนโยบายก่อน จึงจะสามารถเลือกยอมรับได้"}</p></div>
    <p className="mt-2 min-h-4 text-center text-xs text-red-600" role="alert">{p.error}</p><button type="submit" disabled={!ready||p.loading} className="mx-auto mt-1 flex h-12 w-60 items-center justify-center rounded-xl bg-action text-base font-semibold text-white disabled:cursor-not-allowed disabled:bg-disabled disabled:text-[#BDC7D6]">{p.loading?"กำลังส่ง...":"กดรับ OTP"}</button>
  </form>;
}
